#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const xlsx = require('xlsx');

function usage() {
  console.log(`Usage: node excel-to-dict.js <input.xlsx> [outputPath] [format] [sheetName]

  <input.xlsx>   Path to the Excel file (xlsx)
  [outputPath]   Output file path (default: ./output.js or ./output.json depending on format)
  [format]       "js" (default) | "json" — output format
  [sheetName]    Optional sheet name (defaults to first sheet)

Example:
  node excel-to-dict.js data/test.xlsx dist/dict.js js
`);
}

if (process.argv.length < 3) {
  usage();
  process.exit(1);
}

const inputPath = process.argv[2];
let outputPath = process.argv[3] || null;
const format = (process.argv[4] || 'js').toLowerCase();
const sheetName = process.argv[5] || null;

if (!fs.existsSync(inputPath)) {
  console.error(`Input file not found: ${inputPath}`);
  process.exit(2);
}

const workbook = xlsx.readFile(inputPath);
const sheet = sheetName ? workbook.Sheets[sheetName] : workbook.Sheets[workbook.SheetNames[0]];
if (!sheet) {
  console.error('Sheet not found.');
  process.exit(3);
}

const rows = xlsx.utils.sheet_to_json(sheet, {defval: ''});

function findField(row, candidates) {
  // row keys might be in original language; do case-insensitive match against candidates
  const keys = Object.keys(row);
  for (const k of keys) {
    const lk = k.toString().trim().toLowerCase();
    for (const c of candidates) {
      if (lk === c.toLowerCase()) return row[k];
    }
  }
  return undefined;
}

// Expected logical column names - adjust as needed
const projectKeys = ['project', '项目', 'proj', 'module'];
const xpathKeys = ['xpath', 'xPath', '路径', 'path'];
const contentKeys = ['content', '内容', 'value', 'text'];

const result = {};

rows.forEach((r, idx) => {
  const project = (findField(r, projectKeys) || '').toString().trim();
  const xpath = (findField(r, xpathKeys) || '').toString().trim();
  const content = (findField(r, contentKeys) || '').toString();

  if (!project && !xpath) {
    // skip empty rows
    return;
  }

  const proj = project || 'default';
  if (!result[proj]) result[proj] = {};

  if (!xpath) {
    // if xpath absent, try to use a row index as key
    const key = `row_${idx+1}`;
    result[proj][key] = content;
    return;
  }

  // If same xpath already exists, convert to array to hold multiple contents
  if (Object.prototype.hasOwnProperty.call(result[proj], xpath)) {
    const prev = result[proj][xpath];
    if (Array.isArray(prev)) {
      prev.push(content);
    } else {
      result[proj][xpath] = [prev, content];
    }
  } else {
    result[proj][xpath] = content;
  }
});

if (!outputPath) {
  outputPath = format === 'json' ? path.join(process.cwd(), 'output.json') : path.join(process.cwd(), 'output.js');
}

function writeOutput(outPath, fmt, obj) {
  if (fmt === 'json') {
    fs.writeFileSync(outPath, JSON.stringify(obj, null, 2), 'utf8');
    console.log(`Wrote JSON to ${outPath}`);
    return;
  }

  // default: js module export (CommonJS)
  const content = `// Auto-generated by excel-to-dict.js\nmodule.exports = ${JSON.stringify(obj, null, 2)};\n`;
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`Wrote JS module to ${outPath}`);
}

try {
  writeOutput(outputPath, format, result);
} catch (err) {
  console.error('Failed to write output:', err);
  process.exit(4);
}

// exit normally
process.exit(0);
